[tool.poetry]
name = "json_to_md"
version = "0.1.0"
description = ""
authors = ["borontov <anborontov@gmail.com>"]

[tool.poetry.dependencies]
python = "3.9"
Mako = "1.1.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
